/* V12: تفصيل تقديري لحجم كل مستند — قراءة فقط */
(function(){
  var groups=[['students','الطلاب'],['teachers','المعلمون'],['payments','المدفوعات'],['notes','الملاحظات'],['results','النتائج'],['dailyRecords','الرصد اليومي'],['wafdeenStudents','طلاب الوافدين'],['wafdeenTeachers','معلمو الوافدين'],['wafdeenDailyRecords','رصد الوافدين اليومي'],['wafdeenExams','اختبارات الوافدين'],['wafdeenMonthlyReports','تقارير الوافدين الشهرية'],['wafdeenSettings','إعدادات الوافدين'],['wafdeenUsage','استخدام الوافدين']];
  var allRows=[];
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function sizeOf(v){var text=JSON.stringify(v==null?null:v);try{return new Blob([text]).size;}catch(e){return unescape(encodeURIComponent(text)).length;}}
  function fmt(n){n=Number(n)||0;if(n<1024)return n.toLocaleString('ar-EG')+' بايت';if(n<1048576)return (n/1024).toFixed(2)+' KB';return (n/1048576).toFixed(2)+' MB';}
  function labelOf(data,id){var keys=['name','studentName','teacherName','fullName','title','date','recordDate','studentId','grade','className','month','type'];var vals=[];keys.forEach(function(k){var v=data&&data[k];if(v!=null&&String(v).trim()&&vals.length<3)vals.push(k+': '+String(v).slice(0,70));});return vals.length?vals.join(' — '):'مستند بدون اسم ظاهر';}
  function render(){var host=document.getElementById('cloud-record-size-results');if(!host)return;var filter=String((document.getElementById('cloud-record-size-filter')||{}).value||'').trim().toLocaleLowerCase();var visible=allRows.filter(function(r){return !filter||(r.collection+' '+r.group+' '+r.id+' '+r.label).toLocaleLowerCase().includes(filter);});if(!visible.length){host.innerHTML='<p style="padding:12px;background:#fff;border-radius:8px">لا توجد سجلات مطابقة للبحث.</p>';return;}var groupsOut=[];groups.forEach(function(g){var list=visible.filter(function(r){return r.collection===g[0];});if(!list.length)return;var total=list.reduce(function(n,r){return n+r.bytes;},0);var out='<details style="margin:9px 0;background:#fff;border:1px solid #d5e5dc;border-radius:10px;padding:10px"><summary style="cursor:pointer;font-weight:800;color:#174f3e">'+esc(g[1])+' — '+list.length.toLocaleString('ar-EG')+' سجل ظاهر، '+fmt(total)+' إجمالي الظاهر</summary><div class="table-responsive" style="margin-top:10px"><table style="min-width:650px;width:100%"><thead><tr><th>المعرّف</th><th>بيانات تعريفية</th><th>الحجم التقريبي</th></tr></thead><tbody>';list.forEach(function(r){out+='<tr><td dir="ltr" style="word-break:break-all">'+esc(r.id)+'</td><td>'+esc(r.label)+'</td><td><b>'+fmt(r.bytes)+'</b><br><small>'+r.bytes.toLocaleString('ar-EG')+' بايت</small></td></tr>';});out+='</tbody></table></div></details>';groupsOut.push(out);});host.innerHTML=groupsOut.join('');}
  window.filterCloudRecordSizes=render;
  window.refreshCloudRecordSizes=async function(){var status=document.getElementById('cloud-record-size-status'),host=document.getElementById('cloud-record-size-results');if(!status)return;if(!window.db||!window.db.collection){status.textContent='قاعدة البيانات غير متصلة أو لم يتم تسجيل الدخول.';return;}var btn=document.querySelector('#supabase-section-db button[onclick="refreshCloudRecordSizes()"]');if(btn)btn.disabled=true;status.textContent='جارٍ فحص المجموعات واحتساب حجم كل مستند…';if(host)host.innerHTML='';allRows=[];var done=0;try{for(var i=0;i<groups.length;i++){var snap=await window.db.collection(groups[i][0]).get();snap.forEach(function(doc){var data=doc.data()||{};allRows.push({collection:groups[i][0],group:groups[i][1],id:String(doc.id),label:labelOf(data,doc.id),bytes:sizeOf(data)});});done++;status.textContent='تم فحص '+done+' من '+groups.length+' مجموعات؛ '+allRows.length.toLocaleString('ar-EG')+' سجل…';}allRows.sort(function(a,b){return b.bytes-a.bytes;});var total=allRows.reduce(function(n,r){return n+r.bytes;},0);status.textContent='اكتمل الفحص: '+allRows.length.toLocaleString('ar-EG')+' سجل، بإجمالي محتوى مقداره '+fmt(total)+'. السجلات مرتبة من الأكبر إلى الأصغر داخل نتائج كل مجموعة.';render();return {records:allRows.length,estimatedBytes:total};}catch(e){status.textContent='تعذر إكمال الفحص بعد '+allRows.length.toLocaleString('ar-EG')+' سجل: '+String(e&&e.message||e);console.error('Cloud record size scan',e);}finally{if(btn)btn.disabled=false;}};
})();
